### ISSUE TITLE
添加时间限制

### ISSUE THREAD

**Issue by alexsunlee** [ChenLiu-1996/CitationMap#1]
我查完发现查出来的比实际的少，是不是加了类似于近10年的时间限制？

**Comment by ChenLiu-1996** [comment]
Question:
"Did you only scrape the citations in the past 10 years or some other fixed time period? I got fewer citations than expected."

Response:
I don't think I included such a time filter. Some possible reasons for getting fewer citations than expected are listed in the **Limitations** section.
<img width="847" alt="Screenshot 2024-07-29 at 8 50 21 AM" src="https://github.com/user-attachments/assets/58efb361-dc5c-4f85-a3ba-90177813d8b4">
