### ISSUE TITLE
Fix ModuleNotFoundError: No module named 'bibtexparser. "bibdatabase'"

### ISSUE THREAD

**Issue by LostXine** [ChenLiu-1996/CitationMap#10]
## Problem Description

Observed this error: 
```
ModuleNotFoundError: No module named 'bibtexparser. "bibdatabase'"
```
when executing the following command:
```
from citation_map import generate_citation_map
```

## Reason
The latest version of `bibtexparser` (2.0.0b7) seems to have some issues causing this error.

## Solution
Downgrade `bibtexparser` to a stable version 1.4.1 using the following command:
```
pip install bibtexparser==1.4.1
```

**Comment by njzjz** [comment]
I submit to https://github.com/scholarly-python-package/scholarly/issues/546. bibtexparser is not a dependency of CitationMap.

**Comment by LostXine** [comment]
@njzjz Great, thanks for your help!
