### ISSUE TITLE
Yanshan University is shown in Yanshan, Guilin, Guangxi instead of Hebei

### ISSUE THREAD

**Issue by njzjz** [ChenLiu-1996/CitationMap#11]
![image](https://github.com/user-attachments/assets/fe17c788-d1e9-47f6-8007-29fce8d7b811)
![image](https://github.com/user-attachments/assets/16bd6b7e-9a62-4e74-aacc-2b9356ca3bb9)

[citation_map.html](https://github.com/user-attachments/files/16461320/citation_map.html.txt)

**Comment by ChenLiu-1996** [comment]
Hi @njzjz,

Affiliation string localization error is a known problem that I don't have a good solution for yet.

Some famous ones include Amazon (the company) being localized to the Amazon rain forest, and Meta (the company) being localized to a place called Meta in Colombia.

1. One possible solution is to compile an exhaustive list of all possible affiliations and match towards those --- which seems like a lot of work and still does not guarantee accuracy.
2. Another possible solution is to use more intelligent natural language parsing systems such as GPT4, but that requires extra burden on the user which I am not considering right now.

This is one of the reasons I posted an "asking for advice" section, calling for people with expertise in natural language parsing and named entity recognition.

Thanks for understanding the limitations.
