### ISSUE TITLE
Bug: Multiple pages cannot be parsed

### ISSUE THREAD

**Issue by aushimnagarkatti** [ChenLiu-1996/CitationMap#13]
If a paper has more than one page of cited work, the program exits after checking the first page. 
Steps to repro:
1. Find a paper with multiple pages of cited work
2. Run the program and check if output contains papers from the latter pages.

**Comment by aushimnagarkatti** [comment]
I have already fixed this locally, happy to raise a PR with the right branch access

**Comment by ChenLiu-1996** [comment]
I assume you mean the case where there are more than 1 page of citing papers for a cited paper. This is quite unexpected, as I tried to cover this situation: specifically, in https://github.com/ChenLiu-1996/CitationMap/blob/fb3d016542b03b54a9b8a7da32e87b684bf5f0d3/citation_map/scholarly_support.py#L45-L76

With that said, you are very welcome to raise a PR and I will take a look at it.

I believe you can raise a PR if you forked the repository. There should be a "compare and pull request" button on the github website user interface when you push stuff to your own fork, and come back to my repo immediately afterwards. I am not super familiar with handling PRs and this is the main approach I am aware of. Let me know if you have an idea what I can do to facilitate the PR.
