### ISSUE TITLE
[WARNING!] Blocked by CAPTCHA or robot check 

### ISSUE THREAD

**Issue by xuyongxmu** [ChenLiu-1996/CitationMap#15]
How to solve the problem of [WARNING!] Blocked by CAPTCHA or robot check when searching https://scholar.google.com/xxxx?

**Comment by ChenLiu-1996** [comment]
As I mentioned in the documentation, Google scholar officially does not allow webscraping. As a result, the CAPTCHA or blacklisting are expected. My current suggestions are:

1. If you only see the CAPTCHA blockage occasionally for a few authors or papers, you can just ignore that.
