### ISSUE TITLE
An attempt has been made to start a new process before the         current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by zhaoxinf** [ChenLiu-1996/CitationMap#4]
in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Author profile found, with 41 publications.

**Comment by dk-liang** [comment]
`
from citation_map import generate_citation_map

def main():
    scholar_id = 'your_scholar_id'
    generate_citation_map(scholar_id)

if __name__ == '__main__':
    import multiprocessing
    multiprocessing.freeze_support()
    main()
`

**Comment by ChenLiu-1996** [comment]
Contacted by the @zhaoxinf confirming this issue is solved by @dk-liang's solution.

**Comment by ChenLiu-1996** [comment]
I did a test myself. It seems that, at least on my side, protecting your main function with `if __name__ == '__main__'` suffices. Like the following:

```
from citation_map import generate_citation_map

if __name__ == '__main__':
    # This is my Google Scholar ID. Replace this with your ID.
    scholar_id = '3rDjnykAAAAJ'
    generate_citation_map(scholar_id)
```
