### ISSUE TITLE
Could you please tell why I get such return: Converted the institutions to 0 Geocodes? 

### ISSUE THREAD

**Issue by 924973292** [ChenLiu-1996/CitationMap#6]
Finding geographic coordinates from 34 unique citing institutions in 66 entries: 100%|██████████| 34/34 [05:07<00:00,  9.06s/it]

Converted the institutions to 0 Geocodes.

**Comment by 924973292** [comment]
Author: Yang Shu, Institution: HKUST.
Author: Yihui Wang, Institution: HKUST.
Author: Yuan Xie, Institution: East China Normal University.
Author: Yuan Xie, Institution: School of Computer Science.
Author: Yuan Xie, Institution: Technology.
Author: Yuhe Ding, Institution: .
Author: Yuhe Ding, Institution: Anhui University.
Author: Ziyang Wang, Institution: The Alan Turing Institute.
Author: Ziyang Wang, Institution: University of Oxford.

like these...

**Comment by ChenLiu-1996** [comment]
Thanks. Then it confirms it's the second issue -- something wrong with the `geopy` service.

It could be a firewall problem or a temporary unavailability of `geopy` service. You could try using a different IP address (VPN) or simply running it again some later time.

**Comment by 924973292** [comment]
Thanks! I will try that now!

**Comment by 924973292** [comment]
Still not work for different VPN 🥹

**Comment by ChenLiu-1996** [comment]
Very sad! Is it urgent? Maybe you can leave your Google Scholar ID and I can run it for you.

**Comment by mattkczhang** [comment]
My geopy is not working as well. Will try it later and see if it works.

**Comment by mattkczhang** [comment]
Just tested the code out today and got the following output:
-------
Author: Oliver Krebs, Institution: ETH Zürich.
Author: Peter Eppinger, Institution: University of Tübingen.
Author: Satoshi Tanaka, Institution: University of Queensland.
Author: Shawn Arita, Institution: Office of the Chief Economist.
Author: Shawn Arita, Institution: USDA.
Author: Xuepeng Liu, Institution: Kennesaw State University.
Author: jason grant, Institution: Virginia Tech.
Finding geographic coordinates from 38 unique citing institutions in 54 entries: 100%|██████████| 38/38 [02:30<00:00,  3.95s/it]

Converted the institutions to 0 Geocodes.

-------

**Comment by ChenLiu-1996** [comment]
I think the problem likely lies in the `geopy` service. The best bet I have for now is to use a VPN for a different IP address and to check if you are behind a firewall that blocks `geopy`.

**Comment by mattkczhang** [comment]
Just test again under the school ip address and it works!
